### ISSUE TITLE
audiotour_nonworking.ino

### ISSUE THREAD

**Issue by TheNitek** [knopjesmuseum/audioguide#1]
Hi there,
did you get your audiotour_nonworking.ino approach to work? I'm also trying to use SFEMP3Shield with a MFRC522 and they don't realy seem to like each other.

**Comment by companje** [comment]
@TheNitek, no progress unfortunately.

**Comment by TheNitek** [comment]
Well, in case you are still interested. I was able to solve the problem:

For the RFID to work while MP3 plays, you have to change
#define USE_MP3_REFILL_MEANS USE_MP3_INTx
to
#define USE_MP3_REFILL_MEANS USE_MP3_Polled
in SFEMP3Shield.h
and use mp3player.available(); in your loop()

**Comment by companje** [comment]
Thanks!
